server:
  port: 8081
spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/inv_spring_application
    username: inv_manager
    password: Bionic*9&


